stages:
  - dependencies
  - build
  - test
  - check
  - format
  - document

dependencies:linux:
  stage: dependencies
  script:
    - sudo apt update -qq
    - sudo apt -y -qq install qt5-default libqt5websockets5-dev g++ libxml2-utils build-essential doxygen graphviz cppcheck clang-format
    - sudo bash opencv.sh
    - mkdir -p ~/.ssh/
    - sudo ssh-keyscan gitlab.com > ~/.ssh/known_hosts
  except:
    - /^.*-format$/

build:linux:
  stage: build
  script:
    - mkdir build
    - cd build
    - qmake ..
    - make -j6
    - cd ..
  artifacts:
    paths:
      - build/

test:linux:
  stage: test
  script:
    - mkdir build
    - cd build
    - qmake ..
    - make -j6
    - export LD_LIBRARY_PATH=../PiCommunicator
    - make check
  except:
    - /^.*-format$/

check:linux:
  stage: check
  script:
    - cppcheck --error-exitcode=1 . > /dev/null
  except:
    - /^.*-format$/

format:linux:
  stage: format
  script:
    - git remote set-url origin git@gitlab.com:ggwpez/3cpicko.git
    - git branch -D `echo $CI_COMMIT_REF_NAME-format` || true
    - git checkout -b `echo $CI_COMMIT_REF_NAME-format`
    - find . -regex '.*\.\(cc\|h\|hpp\|cpp\)' -exec clang-format -style=file -i {} \;
    - find . -name '*\.html' -type f -exec xmllint --html --output '{}' --format '{}' \;
    - git diff --exit-code || (git add -u && git commit -m"=Auto formatting=" && git push origin HEAD && echo "Created new branch, abort" && exit 1)
  except:
    - /^.*-format$/

document:linux:
  stage: document
  script:
    - doxygen Doxyfile
  except:
    - /^.*-format$/
