before_script:
    - apt update
    - apt -y install qt5-default
    - apt -y install g++
    - apt -y install build-essential
    - apt -y install doxygen

stages:
- build
- test

build_main:
  stage: build
  script:
    - mkdir build
    - cd build
    - qmake ..
    - make
    - make check
    - doxygen Doxyfile
  tags:
    - qt
    - c++