stages:
  - deps
  - build
  - test
  - check
  - format
  - document

pull-deps:docker:
  stage: deps
  script:
    - docker build -f dockerfiles/Dockerfile.deps -t cpicko-deps .
    - docker build -f dockerfiles/Dockerfile.clone -t cpicko-clone .

build-clang:docker:
  stage: build
  script:
    - docker build -f dockerfiles/Dockerfile.clang .

build-gcc:docker:
  stage: build
  script:
    - docker build -f dockerfiles/Dockerfile.gcc -t cpicko-build .

test-gcc:docker:
  stage: test
  script:
    - docker run -w="/src/build/" cpicko-build make check
    
check:docker:
  stage: check
  script:
    - docker run cpicko-build grep -ril ">>>>>>>" --exclude=".gitlab-ci.yml" . && (echo "Found at least one Merge Marker, abort" && exit 1)
    - docker run cpicko-build cppcheck --error-exitcode=1 --force Main/src/ > /dev/null

format:docker:
  stage: format
  script:
    - docker run cpicko-build clang-format --version
    - docker run cpicko-build bash check.sh
  allow_failure:
    true

document:docker:
  stage: document
  script:
    - docker run cpicko-build doxygen Doxyfile > /dev/null 2>&1
