before_script:
  - apt update
  - apt -y install qt5-default g++ build-essential doxygen cppcheck clang-format
  - ssh-keyscan gitlab.com > ~/.ssh/known_hosts

stages:
  - build
  - test
  - format
  - document

build:linux:
  stage: build
  script:
    - mkdir build
    - cd build
    - qmake ..
    - make -j4
    - cd ..
  artifacts:
    paths:
      - build/

test:linux:
  stage: test
  script:
    - mkdir build
    - cd build
    - qmake ..
    - make -j4
    - export LD_LIBRARY_PATH=../PiCommunicator
    - make check

format:linux:
  stage: format
  script:
    - git remote set-url origin git@gitlab.com:ggwpez/3cpicko.git
    - git branch -d `echo $CI_COMMIT_REF_NAME-format` || true
    - git checkout -b `echo $CI_COMMIT_REF_NAME-format`
    - find . -regex '.*\.\(cc\|h\)' -exec clang-format -style=file -i {} \;
    - git diff --exit-code || (git add -u && git commit -m="Auto formating" && git push origin HEAD && echo "Created new branch, abort" && exit 1)
    - cppcheck --error-exitcode=1 . > /dev/null

document:linux:
  stage: document
  script:
    - doxygen Doxyfile