before_script:
    - apt update
    - apt -y install qt5-default g++ build-essential doxygen
    
stages:
- build
- doc
- test

build_main:
  stage: build
  script:
    - mkdir build
    - cd build
    - qmake ..
    - make
    - make check
  tags:
    - qt
    - c++

doc_main:
  stage: doc
  script:
    - doxygen Doxyfile