before_script:
    - apt update
    - apt -y install qt5-default
    - apt -y install g++
    - apt -y install build-essential

stages:
- build
- test

build_main:
  stage: build
  script:
    - mkdir build
    - cd build
    - qmake ..
    - make
  tags:
    - qt
    - c++