before_script:
    - apt update
    - apt install qt5-default
    - apt install g++

stages:
- build
- test

build_main:
  stage: build
  script:
    - mkdir build
    - cd build
    - qmake ..
    - make
  tags:
    - qt
    - c++