stages:
- build
- test

build_main:
  stage: build
  script:
    - echo "#0"
    - mkdir build
    - cd build
    - echo "#1"
    - qmake ..
    - echo "#2"
    - make
    - echo "#3"
  tags:
    - qt
    - c++