image: google/cloud-sdk

services:
  - docker:19.03.11-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375/
  REGISTRY: registry.gitlab.com/ggwpez/3dpicko

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - deps
  - build
  - check
  - deploy

deps:docker:
  stage: deps
  script:
    - docker pull $REGISTRY:deps-ubuntu-18.04 || true
    - docker build --cache-from $REGISTRY:deps-ubuntu-18.04 -f dockerfiles/Dockerfile.deps -t $REGISTRY:deps-ubuntu-18.04 --build-arg OS="ubuntu:18.04" .
    - docker push $REGISTRY:deps-ubuntu-18.04
  only:
    changes:
      - dockerfiles/Dockerfile.deps

build:docker:
  stage: build
  script:
    - docker pull $REGISTRY:dev-ubuntu-18.04 || true
    - docker build --cache-from $REGISTRY:dev-ubuntu-18.04 -f dockerfiles/Dockerfile --target=build --build-arg OS="ubuntu:18.04" --build-arg DEPS="$REGISTRY:deps-ubuntu-18.04" -t $REGISTRY:dev-ubuntu-18.04 .
    - docker push $REGISTRY:dev-ubuntu-18.04

#test:docker:
#  stage: test
#  script:
#    - docker run --rm -w="/3dpicko/build/" 3dpicko-dev:ubuntu-18.04 make test
    
static-check:docker:
  stage: check
  script:
    #- docker run --rm -w="/3dpicko/source" 3dpicko-dev:ubuntu-18.04 grep -ril ">>>>>>>" --exclude=".gitlab-ci.yml" . && (echo "Found at least one Merge Marker, abort" && exit 1)
    - docker run --rm -w="/3dpicko/source" $REGISTRY:dev-ubuntu-18.04 cppcheck --error-exitcode=1 --force Main/src/ > /dev/null
  only:
    changes:
      - Main/**/*
      - server/**/*

format:docker:
  stage: check
  script:
    - docker run --rm -w="/3dpicko/source" $REGISTRY:dev-ubuntu-18.04 bash check.sh
  only:
    changes:
      - check.sh
      - Main/**/*
      - server/**/*
  allow_failure:
    true

document:docker:
  stage: check
  script:
    - docker run --rm -w="/3dpicko/source" $REGISTRY:dev-ubuntu-18.04 doxygen Doxyfile > /dev/null 2>&1
  only:
    changes:
      - Main/**/*
      - Doxyfile

zip:docker:
  stage: deploy
  only:
    - master
  script:
    - docker build --cache-from $REGISTRY:dev-ubuntu-18.04 -f dockerfiles/Dockerfile --target=zip --build-arg OS="ubuntu:18.04" --build-arg DEPS="$REGISTRY:deps-ubuntu-18.04" -t 3dpicko-zip:ubuntu-18.04 .
    - docker run --rm 3dpicko-zip:ubuntu-18.04 > 3DPicko.zip
  artifacts:
    paths:
      - 3DPicko.zip
    expire_in: 2 hrs

container:docker:
  stage: deploy
  only: 
    - master
  script:
    - docker build --cache-from $REGISTRY:dev-ubuntu-18.04 -f dockerfiles/Dockerfile --target=image --build-arg OS="ubuntu:18.04" --build-arg DEPS="$REGISTRY:deps-ubuntu-18.04" -t 3dpicko:dev .
    - docker tag 3dpicko:dev $REGISTRY:dev
    - docker push $REGISTRY:dev

setup-test:docker:
  stage: deploy
  script:
    - docker build --build-arg OS="ubuntu:20.04" -f dockerfiles/Dockerfile.setup-test -t setup-test .
    - (docker run --rm setup-test || true) 2>&1 | grep -qwE "WebSocket  0.0.0.0:8888"
  only:
    - master