stages:
  - deps
  - build
  - test
  - check
  - format
  - document

deps:docker:
  stage: deps
  script:
    - docker build -f Dockerfile.deps -t cpicko-deps .

build:docker:
  stage: build
  script:
    - docker build -f Dockerfile.ci -t cpicko-ci .

test:docker:
  stage: test
  script:
    - docker run -w="/3cpicko/build/" cpicko-ci make check
    
check:docker:
  stage: check
  script:
    - docker run cpicko-ci grep -ril ">>>>>>>" --exclude=".gitlab-ci.yml" . && (echo "Found at least one Merge Marker, abort" && exit 1)
    - docker run cpicko-ci cppcheck --error-exitcode=1 --force Main/src/ > /dev/null

format:docker:
  stage: format
  script:
    - docker run cpicko-ci git checkout -- .
    - docker run cpicko-ci clang-format --version
    - docker run cpicko-ci bash check.sh
  allow_failure:
    true

document:docker:
  stage: document
  script:
    - docker run cpicko-ci doxygen Doxyfile > /dev/null 2>&1
