stages:
- build
- test

build:linux:
  before_script:
    - apt update
    - apt -y install qt5-default g++ build-essential doxygen
  stage: build
  script:
    - mkdir build
    - cd build
    - qmake ..
    - make -j4
    - cd ..
    - doxygen Doxyfile
  artifacts:
    paths:
      - build/

  tags:
    - qt
    - c++

test:linux:
  stage: test
  script:
    - mkdir build
    - cd build
    - qmake ..
    - make -j4
    - export LD_LIBRARY_PATH=../PiCommunicator
    - make check
  tags:
    - test
    - qt
    - c++
