before_script:
    - apt update
    - apt -y install qt5-default g++ build-essential doxygen
    
stages:
- build
- test

build:linux:
  stage: build
  script:
    - mkdir build
    - cd build
    - qmake ..
    - make -j4
    - cd ..
    - doxygen Doxyfile
  tags:
    - qt
    - c++
    

test:linux:
  stage: test
  script:
    - cd build
    - export LD_LIBRARY_PATH=../PiCommunicator
    - make check
  dependencies:
    - build:linux
  tags:
    - test
    - qt
    - c++
