# SPDX-FileCopyrightText: 2018-2020 Oliver Tale-Yazdi <oliver@tasty.limo>
#
# SPDX-License-Identifier: GPL-3.0-only

ARG OS
FROM $OS AS build

LABEL maintainer "Oliver Tale-Yazdi <oliver@tasty.limo>"

# Install tzdata, sudo + git so they dont not annoy us later
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
	apt-get update && apt-get install -y sudo tzdata git
RUN useradd -ms /bin/bash docker && \
	su docker

ENV CPICKO_ENV=docker
ENV CPICKO_USER=docker
WORKDIR /src/
COPY . .
RUN bash dependencies.sh && \
	bash opencv.sh && \
	bash setup.sh /install

WORKDIR /install/
ENV LD_LIBRARY_PATH=/install/
CMD [ "timeout", "5", "bash", "start.sh" ]
