FROM cpicko-deps as clone

WORKDIR /src/
RUN git submodule init
RUN git submodule update
RUN mkdir build/
WORKDIR /src/build/

# Clang build
FROM clone as clang
RUN qmake -spec linux-clang ..
RUN make -j$(nproc) > /dev/null

# GCC build
FROM clone as build
RUN qmake ..
RUN make -j$(nproc) > /dev/null
WORKDIR /src/